name: Auto-push toutes les 4 heures

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  auto-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Spécifiez la version de Node.js que vous souhaitez utiliser

    steps:
    - name: Utiliser Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Configuration de l'utilisateur Git
      run: |
        git config --global user.name "ALFRED-TERNYNCK"
        git config --global user.email "ternynckalfred@gmail.com"

    - name: Commit et push
      run: |
        git add -A
        git commit -m "Auto-push toutes les 4 heures"
        git push
