name: Auto-push de fichier toutes les 2 heures

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le répertoire actuel
      run: pwd  # Affiche le répertoire de travail actuel

    - name: Configuration de l'utilisateur Git
      run: |
        git config --global user.name "Alfred-TERNYNCK"
        git config --global user.email "ternynckalfred@gmail.com"

    - name: Créer un fichier vide avec un horodatage
      run: |
        echo "Fichier vide créé le $(date)" > new_file.txt

    - name: Commit du nouveau fichier
      run: |
        git add new_file.txt
        git commit -m "Ajout d'un fichier avec horodatage"
        git push

    - name: Supprimer le fichier précédent (s'il existe)
      run: |
        if [ -f old_file.txt ]; then
          git rm old_file.txt
          git commit -m "Suppression du fichier précédent"
          git push
        fi

    - name: Renommer le fichier créé pour le prochain cycle
      run: mv new_file.txt old_file.txt
