name: Test de connexion GitHub

on:
  push:
    branches:
      - main  # Déclencher le workflow sur les pushes vers la branche principale

jobs:
  test-connexion:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le répertoire actuel
      run: pwd  # Affiche le répertoire de travail actuel

    - name: Afficher les informations sur l'environnement
      run: env  # Affiche les variables d'environnement

    - name: Configuration de l'utilisateur Git
      run: |
        git config --global user.name "YOUR_USERNAME"
        git config --global user.email "YOUR_EMAIL@example.com"

    - name: Afficher l'état de la configuration Git
      run: git config --list

    - name: Cloner le référentiel GitHub
      run: git clone https://github.com/Alfred-TERNYNCK/git@github.com:Alfred-TERNYNCK/workflow.git test_clone
      # Remplacez YOUR_USERNAME et YOUR_REPOSITORY par votre nom d'utilisateur GitHub et le nom de votre référentiel

    - name: Afficher le contenu du répertoire cloné
      run: ls -al test_clone
