name: Auto-push de fichier vide toutes les 4 heures

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le répertoire actuel
      run: pwd  # Affiche le répertoire de travail actuel

    - name: Définir le répertoire de travail
      run: cd $GITHUB_WORKSPACE
      shell: bash

    - name: Créer un fichier vide
      run: |
        touch new_file.txt
        echo "Fichier vide créé pour le push automatique" > new_file.txt

    - name: Configuration de l'utilisateur Git
      run: |
        git config --global user.name "ALFRED-TERNYNCK"
        git config --global user.email "ternynckalfred@gmail.com"

    - name: Commit et push du fichier vide
      run: |
        git add new_file.txt
        git commit -m "Ajout d'un fichier vide pour le push automatique"
        git push
